#' PET calculation by Baier and Robertson method
#'
#' Function to calculate pet 
#'
#' @importFrom raster calc 
#' 
#' @param x a RasterBrick object generated by \code{\link{pet_aux}}  
#' @param tavg a RasterBrick object having average temperature 
#' @return a RasterBrick object
#' @keywords internal
#' @examples 
#' \dontrun{
#' x <- tavg.nc  or character string with path to data file 
#' x_brick <- raster::brick(x) 
#' pet <- pet_br(tavg = x_brick)
#' }

pet_br <- function(tmax,tmin){
  BR_1 <- 0.109
  BR_2 <- 0.157
  BR_3 <- 0.158
  BR_4 <- 5.39
  pet_br <- BR_1*pet_aux(tmax) + BR_2*tmax + BR_3*(tmax - tmin) - BR_4
  pet_br <- calc(pet_br, fun = function(y){ifelse(y < 0, 0, y)})
  return(pet_br)
}