#' Evapotranspiration line plot
#'
#' Function for plotting (line) time-series of area averaged Evapotranspiration.
#'
#' @import ggplot2
#' @param x a csv generated by \code{\link{make_ts}}
#' @return ggplot object
#' @export

plot_line <- function(x){
  x$date <- as.Date(x$date) # Convert time to date
  
  p00 <- ggplot(x, aes(x = date, y = value, color = "#ff7f00")) + 
    geom_line() +
    theme_bw() +
    labs(x = NULL, y = "[mm]", title = "Evapotranspiration") +
    scale_x_date(breaks = seq(as.Date("1840/1/1"), as.Date("2050/1/1"), 
                              by = "10 year"), date_labels = "%Y") +
    theme(plot.title = element_text(size=24),
          axis.text = element_text(size = 20),
          axis.title = element_text(size = 24), 
          legend.position = "none")
  return(p00)
}
